# Generated by Django 3.1.3 on 2020-12-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201117_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='blog.classroom'),
        ),
    ]
