# Generated by Django 3.1.3 on 2020-12-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201209_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_set', to='blog.classroom'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='blog.forum'),
        ),
    ]
