# Generated by Django 3.1.3 on 2020-12-24 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
