# Generated by Django 3.1.3 on 2020-12-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_response_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='post_file'),
        ),
    ]
