# Generated by Django 3.1.3 on 2020-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_field',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='post_file'),
        ),
    ]
