# Generated by Django 3.1.3 on 2021-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
